name: PyPi Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.8
        with:
          python_version: 3.8
          #          poetry_version: 1.1.5
          pypi_token: ${{ secrets.PYPI_API_TOKEN }}
